apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-certs
type: Opaque
data:
  rabbitmq.p12: # base64 encoded content of rabbitmq.p12
  ca.crt: # base64 encoded content of ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: client-certs
type: Opaque
data:
  client-truststore.p12: # base64 encoded content of client-truststore.p12
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    listeners.ssl.default = 5671
    ssl_options.certfile = /etc/rabbitmq/certs/rabbitmq.p12
    ssl_options.certfile_password = MyKeystorePass
    ssl_options.cacertfile = /etc/rabbitmq/certs/ca.crt
    ssl_options.verify = verify_none
    ssl_options.fail_if_no_peer_cert = false