# Secrets are created dynamically in the workflow
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    listeners.ssl.default = 5671
    ssl_options.certfile = /etc/rabbitmq/certs/server.crt
    ssl_options.keyfile = /etc/rabbitmq/certs/server.key
    ssl_options.cacertfile = /etc/rabbitmq/certs/ca.crt
    ssl_options.verify = verify_none
    ssl_options.fail_if_no_peer_cert = false