name: Deploy to Minikube

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted  # Use your local machine as runner
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
      
    - name: Build JAR
      run: ./gradlew clean build -x test

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        eval $(minikube docker-env)
        
    - name: Build Docker image
      run: |
        eval $(minikube docker-env)
        docker build -t rabbitmq-consumer:${{ github.sha }} .
        
    - name: Create certificate files from secrets
      run: |
        echo "${{ secrets.RABBITMQ_P12 }}" | base64 -d > rabbitmq.p12
        echo "${{ secrets.CA_CRT }}" | base64 -d > ca.crt
        echo "${{ secrets.CLIENT_TRUSTSTORE_P12 }}" | base64 -d > client-truststore.p12
        
        # Extract PEM files from P12 for RabbitMQ
        openssl pkcs12 -in rabbitmq.p12 -out server.crt -clcerts -nokeys -passin pass:MyKeystorePass
        openssl pkcs12 -in rabbitmq.p12 -out server.key -nocerts -nodes -passin pass:MyKeystorePass
        
    - name: Create certificate secrets
      run: |
        kubectl create secret generic rabbitmq-certs --from-file=server.crt --from-file=server.key --from-file=ca.crt --dry-run=client -o yaml | kubectl apply -f -
        kubectl create secret generic client-certs --from-file=client-truststore.p12 --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f manifests/rabbitmq-deployment.yaml
        envsubst < manifests/deployment.yaml | kubectl apply -f -
      env:
        IMAGE_TAG: ${{ github.sha }}
        
    - name: Verify deployment
      run: kubectl get pods