name: Deploy to Minikube

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted  # Use your local machine as runner
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
      
    - name: Build JAR
      run: ./gradlew clean build -x test

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        eval $(minikube docker-env)
        
    - name: Build Docker image
      run: |
        eval $(minikube docker-env)
        docker build -t rabbitmq-consumer:${{ github.sha }} .
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f manifests/rabbitmq-deployment.yaml
        envsubst < manifests/deployment.yaml | kubectl apply -f -
      env:
        IMAGE_TAG: ${{ github.sha }}
        
    - name: Verify deployment
      run: kubectl get pods